/* Integrate equations of motion of an elastic rod */
#include "proto.h"

#define symplectic_algo

//#define autoAR

//#define D_calculations       // made D calculations valgrind clean
//#define overlapping_D_cal
//#define nonoverlapping_D_cal

//#define lessdata
#define animation
#define small_animation_file
//#define normal_modes          // --> Not yet converted to the new grid system
//#define nodalenergy
//#define positionfileON
#define tip2tip
#define head_vorticella

unsigned short Xi[3];

int main (int argc, char **argv)
{
  struct rod *rod; 
  struct node *pn, *pn1, *pn2;
  struct elem *pe;

  int   seed, n_rods, n, k, tracker;
  FILE  *file_ptr=0;

  if (argc < 7)
    {printf("\n Too few arguments to the C code, bailing out. \n");
      exit(0); }

  N  	 = atoi(argv[1]);
  dt 	 = atof(argv[2]);
  AR     = atof(argv[3]);
  nt  	 = atoi(argv[4]);	  //number of iterations
  tprint = atoi(argv[5]);	  //how many iterations to save after
  seed	 = atoi(argv[6]);

  LENGTH = AR*DIA;  // length of each segment
  Nexvol = 2*(int)ceil(cutoffD/LENGTH); // number of adjcent nodes to be dropped from exvol force. Its 2*cutoffD to avoid affecting compression of rod in linear regime.
  
  srand(seed);   // This seed determines the exact numbers generated by rand()
  Xi[0] = rand();
  Xi[1] = rand();
  Xi[2] = rand();

  strcpy(datadir,"data");

#ifdef autoAR
  AR = 2*tan(Pi/N)/fabs(OMEGA_1);     // used when midpoint of elements are placed on circle
  char ar_s[64];
  sprintf( ar_s,"%.4f", AR);
#endif
  
  strcat(datadir,"-");
  strcat(datadir,argv[1]);
  strcat(datadir,"-");
  strcat(datadir,argv[2]);
  strcat(datadir,"-");
#ifdef autoAR
  strcat(datadir,ar_s);
#else
  strcat(datadir,argv[3]);
#endif
  strcat(datadir,"-");
  strcat(datadir,argv[4]);
  strcat(datadir,"-");
  strcat(datadir,argv[5]);
  strcat(datadir,"-");
  strcat(datadir,argv[6]);

  char origdir[64];  
  strcpy(origdir,datadir);
#ifdef checkpoint_resume
  strcat(datadir,"-resume");
#endif

  char command[64]={"mkdir "};
  strcat(command,datadir);
  if (system(command) != 0) // You must check if the command was successful
    {printf("mkdir not successful, bailing out \n");exit(1);}

#ifdef D_calculations

  real *t1, *t2, *tau;
  real *x1, *x2, *y1, *y2, *z1, *z2, *sqdisp, *msd, *stddev;
  real *tauinit, *t1init, *x1init, *y1init, *z1init, *sqdispinit, *msdinit, *stddevinit;
  int factor;

  if (nt <=100000)                        {factor = 1;     }
  if (nt <=1000000     && nt >100000)     {factor = 10;    }
  if (nt <=10000000    && nt >1000000)    {factor = 100;   }
  if (nt <=100000000   && nt >10000000)   {factor = 1000;  }
  if (nt <=1000000000  && nt >100000000)  {factor = 10000; }
  //  if (nt > 1000000000) {printf("Too long \n"); exit(0);}
  //  if (nt <=10000000000 && nt >1000000000) {factor = 100000;}

  tau	= (real *) calloc(nt/factor+ 1, sizeof(real));
  msd	= (real *) calloc(nt/factor+ 1, sizeof(real));
  stddev= (real *) calloc(nt/factor+ 1, sizeof(real));
  t1 	= (real *) calloc(nt/factor+ 1, sizeof(real));
  x1 	= (real *) calloc(nt/factor+ 1, sizeof(real));
  y1 	= (real *) calloc(nt/factor+ 1, sizeof(real));
  z1 	= (real *) calloc(nt/factor+ 1, sizeof(real));
  sqdisp= (real *) calloc(nt/factor+ 1, sizeof(real));
  // storing the original position of pointers for freeing memory later
  tauinit    = tau   ;
  msdinit    = msd   ;
  stddevinit = stddev;
  t1init     = t1    ;
  x1init     = x1    ;
  y1init     = y1    ;
  z1init     = z1    ;
  sqdispinit = sqdisp;
  
#endif

  M0 = 0;
  //M0 = (N+1)/2;   // if N=1 then M0 = 0 because M0 is an int, so CoM is at 0.5

  n_rods = 1;
  rod = (struct rod *) calloc(n_rods, sizeof(struct rod));

  /////// Initialization //////
  init(rod, n_rods, datadir);

  // populate the positions and momenta
  pop(rod, n_rods, origdir);

  popspas(rod);
 
  tracker = 0; // tracker must be set to zero at the beginning of iterations, its job is to track the position of pointers for diffusivity calculation
  // For Basset force calculation
#ifdef Basset

  TAU = (real *) calloc(tprint + 1, sizeof(real));
  phx = (real *) calloc(tprint + 1, sizeof(real)); 
  phy = (real *) calloc(tprint + 1, sizeof(real)); 
  phz = (real *) calloc(tprint + 1, sizeof(real)); 
  lh1 = (real *) calloc(tprint + 1, sizeof(real)); 
  lh2 = (real *) calloc(tprint + 1, sizeof(real)); 
  lh3 = (real *) calloc(tprint + 1, sizeof(real)); 

  TAUavg = (real *) calloc(nt+ 1, sizeof(real));
  phxavg = (real *) calloc(nt+ 1, sizeof(real)); 
  phyavg = (real *) calloc(nt+ 1, sizeof(real)); 
  phzavg = (real *) calloc(nt+ 1, sizeof(real)); 
  lh1avg = (real *) calloc(nt+ 1, sizeof(real)); 
  lh2avg = (real *) calloc(nt+ 1, sizeof(real)); 
  lh3avg = (real *) calloc(nt+ 1, sizeof(real));
 
  indx = 0; avgindx = 0;
#endif

  /////// Iterations //////

  T=0.0; VISCOCITY= 0.001; friction(rod, dt, 1); frictionSphere(rod, dt, 1);

  real temp1=0.0, temp2=0.0;

  for (; t <= nt; t++ )
    { 
      temp1 = 1-pow(t/(nt+1),0.05);

      VISCOCITY= 0.001;

      if (t%tprint == 0)
	{ 
	  /*
	    com(rod);
	    char comfile[64];
	    strcpy(comfile,datadir);
	    strcat(comfile, "/com.ods");
	    file_ptr = fopen (comfile, "a");
	    fprintf (file_ptr, "%.3f \t  % .12e \t % .12e \t % .12e \t % .12e \t % .12e \t % .12e \t % .12e \t % .12e \t % .12e \n", t*dt, rod->xcm, rod->ycm, rod->zcm, rod->pxcm, rod->pycm, rod->pzcm, rod->lxcm, rod->lycm, rod->lzcm );
	    fclose (file_ptr);
	  */

	  energy(rod); // Also for nodal energies    
	  char energyfileS[64];
	  strcpy(energyfileS,datadir);
	  strcat(energyfileS, "/energyS.ods");
	  file_ptr = fopen (energyfileS, "a");    
	  fprintf (file_ptr, "%.3f \t %.15f \t %.15f \t %.15f \t %.15f \n", t*dt, rod->pe, rod->ke, rod->peS, rod->pe+rod->ke+rod->peS);
	  fclose (file_ptr);
    
	  char energyfile[64];
	  strcpy(energyfile,datadir);
	  strcat(energyfile, "/energy.ods");
	  file_ptr = fopen (energyfile, "a");    
	  fprintf (file_ptr, "%.3f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \t %.15f \n", t*dt, rod->pe, rod->ke, rod->pe+rod->ke, rod->peT1, rod->peT2, rod->peT3, rod->peR1, rod->peR2, rod->peR3, rod->keT1, rod->keT2, rod->keT3, rod->keR1, rod->keR2, rod->keR3);
	  fclose (file_ptr);


#ifdef tip2tip
	  char tip[64];
	  strcpy(tip,datadir);
	  strcat(tip, "/tip.ods");
	  file_ptr = fopen(tip, "a");
	  pn2 = &rod[0].nodes[rod[0].n_nodes-2-ex_seg];
	  pn1 = &rod[0].nodes[1];
	  //fprintf(file_ptr, "%f %.16e %.16e %.16e %.16e %.16e\n", t*dt, pn2->rx - pn1->rx,  pn2->ry - pn1->ry,  pn2->rz - pn1->rz, sqrt((pn2->rx-pn1->rx)*(pn2->rx-pn1->rx)+(pn2->ry-pn1->ry)*(pn2->ry-pn1->ry)+(pn2->rz-pn1->rz)*(pn2->rz-pn1->rz)), pn2->pz);
	  fprintf(file_ptr, " %f %.16e %.16e %.16e %.16e %.16e\n", t*dt, pn2->rx - pn1->rx,  pn2->ry - pn1->ry,  pn2->rz - pn1->rz, sqrt((pn2->rx - pn1->rx)*(pn2->rx - pn1->rx)+  (pn2->ry - pn1->ry)*(pn2->ry - pn1->ry)+ (pn2->rz - pn1->rz)*(pn2->rz - pn1->rz)), -100*pn2->pz/(headmass*rod->xm) );

	  fclose (file_ptr);
#endif
	  char power[64];
	  strcpy(power,datadir);
	  strcat(power, "/power.ods");
	  file_ptr = fopen(power, "a");
	  pn2 = &rod[0].nodes[rod[0].n_nodes-2-ex_seg];
	  fprintf(file_ptr, " %f %.16e \n", t*dt, 1000*6*Pi*VISCOCITY*HeadRad*(pn2->pz/(headmass*rod->xm))*(pn2->pz/(headmass*rod->xm)) );
	  fclose (file_ptr);
	}
 
#ifdef animation
      char animationfile[64];
      strcpy(animationfile,datadir);
      strcat(animationfile, "/animation.gro");
      file_ptr = fopen(animationfile, "a");
 
#ifdef small_animation_file		
      if (t%(10*tprint) == 0)	
#else
	if (t%(tprint) == 0)	
#endif
	  {
	    fprintf (file_ptr,"t=%.4f \n %3i \n", dt*t, N);
       
	    for (k = 0; k < rod[0].n_nodes; k++)
	      {
		pn = &rod[0].nodes[k];
		pe = &rod[0].elems[k];
		//		fprintf (file_ptr, "1OXYGEN \t OW1 \t %i \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \t % .16e \n", k, pn->rx, pn->ry, pn->rz, pn->q0, pn->qx, pn->qy, pn->qz, pn->px, pn->py, pn->pz, pn->l1, pn->l2, pn->l3 );
		fprintf (file_ptr, "1OXYGEN \t OW1 \t %i \t %.16e \t %.16e \t %.16e \n", k, pn->rx, pn->ry, pn->rz);
	      }
	    fprintf (file_ptr,"%.2f \t %.2f \t %.2f \n",10.0,10.0,10.0);
	  }
      fclose (file_ptr);

      char spasmoneme[64];
      strcpy(spasmoneme,datadir);
      strcat(spasmoneme, "/spasmo.gro");
      file_ptr = fopen(spasmoneme, "a");
 
#ifdef small_animation_file		
      if (t%(10*tprint) == 0)	
#else
	if (t%(tprint) == 0)	
#endif
	  {
	    fprintf (file_ptr,"t=%.4f \n %3i \n", dt*t, N);
       
	    for (k = 0; k < rod[0].n_nodes; k++)
	      {
		pn = &rod[0].nodes[k];
		pe = &rod[0].elems[k];
		fprintf (file_ptr, "1OXYGEN \t OW1 \t %i \t %.16e \t %.16e \t %.16e \n", k, pn->xx, pn->xy, pn->xz );
	      }
	    fprintf (file_ptr,"%.2f \t %.2f \t %.2f \n",10.0,10.0,10.0);
	  }
      fclose (file_ptr);

#ifdef head_vorticella
      char head[64];
      strcpy(head,datadir);
      strcat(head, "/head.gro");
      file_ptr = fopen(head, "a");

#ifdef small_animation_file		
      if (t%(10*tprint) == 0)	
#else
	if (t%(tprint) == 0)	
#endif
	  {
	    fprintf (file_ptr,"t=%.2f \n %i \n", dt*t, 1);

	    pn2 = &rod[0].nodes[rod[0].n_nodes-2];
	    pn1 = &rod[0].nodes[1];
	    fprintf(file_ptr,"1OXYGEN \t OW1 \t %i \t %.16e \t %.16e \t %.16e \n", 1,  pn2->rx - pn1->rx,  pn2->ry - pn1->ry,  pn2->rz - pn1->rz );
     
	    fprintf (file_ptr,"%.2f \t %.2f \t %.2f \n",10.0,10.0,10.0);
	  }
      fclose (file_ptr);
#endif

#endif
 
      if (t%(100*tprint) == 0)	
	{
	  char checkpoint[64];
	  strcpy(checkpoint,datadir);
	  strcat(checkpoint, "/checkpoint.ods");
	  file_ptr = fopen(checkpoint, "a");
	  fprintf(file_ptr,"%i %i %i %i \n",t,Xi[0],Xi[1],Xi[2]);
	  for(k=0; k< rod[0].n_nodes; k++)
	    {
	      pn = &rod[0].nodes[k];
	      fprintf (file_ptr, "%i \t %.16f \t %.16f  \t %.16f  \t %.16f  \t %.16f  \t %.16f \t  %.16f \t  %.16f  \t %.16f  \t %.16f  \t %.16f  \t %.16f  \t %.16f \n", k, pn->rx, pn->ry, pn->rz, pn->q0, pn->qx, pn->qy, pn->qz, pn->px, pn->py, pn->pz, pn->l1, pn->l2, pn->l3 );
	    }      
	  fclose (file_ptr);
	}
 
#ifdef D_calculations      
      if(t%factor == 0)
	{			
	  *x1 = rod->xcm; 	x1++ ;
	  *y1 = rod->ycm; 	y1++ ;
	  *z1 = rod->zcm; 	z1++ ;
	  *t1 = t*dt;        t1++ ;
	  tracker++;
#ifdef positionfileON		
	  char positionfile[64];
	  strcpy(positionfile,datadir);
	  strcat(positionfile, "/positions.ods");
	  file_ptr = fopen(positionfile, "a");
	  fprintf(file_ptr, " %.2f \t %.15e \t %.15e \t %.15e \n", t*dt, rod->xcm, rod->ycm, rod->zcm);
	  fclose (file_ptr);		
#endif
	}		      
#endif
 
      propagator(rod, dt, n_rods);

    }
  
#ifdef overlapping_D_cal
  real fraction = 0.2;
  real tempsum = 0.0;
  int tauvalue = 1;
  t1 = t1-tracker;	 //setting the pointer back
  x1 = x1-tracker;	 //setting the pointer back
  y1 = y1-tracker;	 //setting the pointer back
  z1 = z1-tracker;	 //setting the pointer back

  for(tauvalue=1;tauvalue<=fraction*nt/factor;tauvalue++,tau++,msd++,stddev++)
    {
      t2 = t1 + tauvalue;
      x2 = x1 + tauvalue;
      y2 = y1 + tauvalue;
      z2 = z1 + tauvalue;
      *tau = *t2 - *t1;

      for (t=0;t<nt/factor-tauvalue;t++,x1++,x2++,y1++,y2++,z1++,z2++,sqdisp++)
	{ *sqdisp = (*x2-*x1)*(*x2-*x1) + (*y2-*y1)*(*y2-*y1) + (*z2-*z1)*(*z2-*z1); }

      sqdisp = sqdisp -(nt/factor-tauvalue);  //setting the pointer back

      tempsum = 0.0;
      for (t=0;t<nt/factor-tauvalue;t++,sqdisp++)
	{ tempsum = tempsum + *sqdisp; }
      *msd = tempsum/(nt/factor-tauvalue);

      tempsum = 0.0;
      sqdisp = sqdisp -(nt/factor-tauvalue);  //setting the pointer back
      /*
	for (t=0;t<nt/factor-tauvalue;t++,sqdisp++)
	{ tempsum = tempsum + (*sqdisp-*msd)*(*sqdisp-*msd); }
	*stddev = sqrt(tempsum/(nt/factor-tauvalue));
	sqdisp = sqdisp -(nt/factor-tauvalue);  //setting the pointer back
      */
      x1 = x1-(nt/factor-tauvalue); //setting the pointer back
      y1 = y1-(nt/factor-tauvalue); //setting the pointer back
      z1 = z1-(nt/factor-tauvalue); //setting the pointer back

      if (nt>= 10000000 && tauvalue%tprint == 0)
	{printf("tauvalue: %d \n", tauvalue);}
    }

  char msdfile[64];
  strcpy(msdfile,datadir);
  strcat(msdfile, "/msd_overlap.ods");
  file_ptr = fopen (msdfile, "a");

  tau 	 = tau - (tauvalue - 1);
  msd 	 = msd - (tauvalue - 1);
  stddev = stddev - (tauvalue - 1);
	
  for(t =1;t<fraction*nt/factor;t++,tau++,msd++,stddev++) // its t<fraction*nt/factor and not <= because we are differencing
    {
      if (t%(tprint/factor) == 0)
	{fprintf (file_ptr, "%.2f \t %.15f \t %.15f \n", *tau, *msd/6, (*(msd+1) - *(msd))/(6*( *(tau+1)-*(tau))) ); }
    }
  fclose (file_ptr);

  // restoring the pointers back to the original location for the purpose of freeing meemory
  tau	    = tauinit    ;
  msd	    = msdinit    ;
  stddev    = stddevinit ;
  t1 	    = t1init     ;
  x1 	    = x1init     ;
  y1 	    = y1init     ;
  z1 	    = z1init     ;
  sqdisp    = sqdispinit ;

  free(tau); 
  free(msd); 
  free(stddev);
  free(t1); 
  free(x1); 
  free(y1); 
  free(z1); 
  free(sqdisp); 
  
#endif

#ifdef nonoverlapping_D_cal

  real fraction = 0.2;
  real tempsum = 0.0;
  int tauvalue = 1;
  t1 = t1-tracker;	 //setting the pointer back
  x1 = x1-tracker;	 //setting the pointer back
  y1 = y1-tracker;	 //setting the pointer back
  z1 = z1-tracker;	 //setting the pointer back

  for(tauvalue=1;tauvalue<=fraction*nt/factor;tauvalue++,tau++,msd++,stddev++)
    {
      t2 = t1 + tauvalue;
      x2 = x1 + tauvalue;
      y2 = y1 + tauvalue;
      z2 = z1 + tauvalue;
      *tau = *t2 - *t1;

      tracker = 0;
      for (t=0;t<nt/factor-tauvalue;t=t+tauvalue,x1=x1+tauvalue,x2=x2+tauvalue,y1=y1+tauvalue,y2=y2+tauvalue,z1=z1+tauvalue,z2=z2+tauvalue,sqdisp++,tracker++)
	{ *sqdisp = (*x2-*x1)*(*x2-*x1) + (*y2-*y1)*(*y2-*y1) + (*z2-*z1)*(*z2-*z1); }

      sqdisp = sqdisp - tracker;  //setting the pointer back

      tempsum = 0.0;
      for (t=0;t<tracker;t++,sqdisp++)
	{ tempsum = tempsum + *sqdisp; }
      *msd = tempsum/tracker;

      sqdisp = sqdisp - tracker;  //setting the pointer back
      /*
	tempsum = 0.0;
	for (t=0;t<tracker;t++,sqdisp++)
	{ tempsum = tempsum + (*sqdisp-*msd)*(*sqdisp-*msd); }
	*stddev = sqrt(tempsum/tracker);
	sqdisp = sqdisp - tracker;    //setting the pointer back
      */
      x1 = x1-(tracker*tauvalue); 	//setting the pointer back
      y1 = y1-(tracker*tauvalue); 	//setting the pointer back
      z1 = z1-(tracker*tauvalue); 	//setting the pointer back

      if (nt>= 10000000 && tauvalue%tprint == 0)
	{printf("tauvalue: %d \n", tauvalue);}
    }
  char msdfile[64];
  strcpy(msdfile,datadir);
  strcat(msdfile, "/msd_nonoverlap.ods");
  file_ptr = fopen (msdfile, "a");

  tau 	 = tau - (tauvalue - 1);
  msd 	 = msd - (tauvalue - 1);
  stddev = stddev - (tauvalue - 1);

  for(t =1;t<fraction*nt/factor;t++,tau++,msd++,stddev++)
    {
      if (tprint*fraction < 1)
	{	printf("tprint too small for the used fraction = %f, increase tprint by an order. Exiting \n", fraction);
	  exit(0);
	}
      if (t%((int)(tprint*fraction)/factor) == 0)
	{fprintf (file_ptr, "%.2f \t %.15f \t %.15f \n", *tau, *msd/6, (*(msd+1) - *(msd))/(6*( *(tau+1)-*(tau))) ); }
    }
  fclose (file_ptr);

  // restoring the pointers back to the original location for the purpose of freeing meemory
  tau	    = tauinit    ;
  msd	    = msdinit    ;
  stddev    = stddevinit ;
  t1 	    = t1init     ;
  x1 	    = x1init     ;
  y1 	    = y1init     ;
  z1 	    = z1init     ;
  sqdisp    = sqdispinit ;

  free(tau); 
  free(msd); 
  free(stddev);
  free(t1); 
  free(x1); 
  free(y1); 
  free(z1); 
  free(sqdisp); 

#endif

  //Free memory
  for (n = 0; n < n_rods; n++)
    {
      free(rod[n].nodes);
      free(rod[n].elems);
      free(rod);
    }

#ifdef Basset
  free(TAU); free(TAUavg);               	     
  free(phx); free(phxavg);
  free(phy); free(phyavg);
  free(phz); free(phzavg);
  free(lh1); free(lh1avg);
  free(lh2); free(lh2avg);
  free(lh3); free(lh3avg);
#endif

  return(0);
}
